# Generated by Django 4.1.3 on 2022-11-11 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم :')),
                ('who_i', models.TextField(verbose_name=' من انا :')),
                ('proce', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف :')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='صورة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
