# Generated by Django 4.1.3 on 2022-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0002_profile_slug_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proce',
            new_name='price',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=' المحافظة :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نبذة عنك :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعات العمل:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, verbose_name='الاسم :'),
        ),
    ]
