# Generated by Django 4.1.3 on 2022-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0003_rename_proce_profile_price_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
