# Generated by Django 4.1.3 on 2022-11-14 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0004_profile_facebook_profile_gmail_profile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
