# Generated by Django 4.1.3 on 2022-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0005_profile_join_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('f', 'female')], max_length=50, null=True),
        ),
    ]
