# Generated by Django 4.1.3 on 2022-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0006_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Specialization',
            field=models.CharField(blank=True, choices=[('جلدية', 'جلدية'), ('أسنان', 'أسنان'), ('نساء وتوليد', 'نساء وتوليد'), ('نفسي', 'نفسي'), ('اطفال حديثي الولادة', 'اطفال حديثي الولادة'), ('مخ واعصاب', 'مخ واعصاب'), ('عظام', 'عظام'), ('انف واذن وحنجرة', 'انف واذن وحنجرة'), ('قلب واوعية دموية', 'قلب واوعية دموية'), ('اورام', 'اورام'), ('باطنة', 'باطنة'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('جراحة اطفال', 'جراحة اطفال'), ('جراحة اوعية دموية', 'جراحة اوعية دموية'), ('جراحة اورام', 'جراحة اورام'), ('جراحة تجميل', 'جراحة تجميل'), ('جراحة سمنة ومناظير', 'جراحة سمنة ومناظير')], max_length=50, null=True),
        ),
    ]
