# Generated by Django 4.1.3 on 2022-11-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0009_alter_profile_specialization_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_plugin', models.CharField(max_length=150, verbose_name='عنوان المقال')),
                ('plugin', models.CharField(max_length=500, verbose_name='المقال')),
            ],
        ),
    ]
