# Generated by Django 4.1.3 on 2012-12-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0011_newpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='صورة للمقال'),
        ),
    ]
