# Generated by Django 4.1.3 on 2022-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0013_alter_newpost_title_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='plugin',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='title_plugin',
            field=models.CharField(max_length=150, verbose_name='عنوان المقال'),
        ),
    ]
