# Generated by Django 4.1.3 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentdef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الأسم ')),
                ('phone', models.IntegerField(verbose_name='رقم الهاتف')),
                ('gmail', models.CharField(max_length=50, verbose_name='البريد الالكتروني ')),
            ],
        ),
    ]
