# Generated by Django 4.1.3 on 2022-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0018_newpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpost',
            old_name='user',
            new_name='realtion',
        ),
    ]
