# Generated by Django 4.1.3 on 2022-12-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vezeta', '0020_alter_newpost_realtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='realtion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
