# Generated by Django 4.1.3 on 2012-12-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vezeta', '0021_alter_newpost_realtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpost',
            old_name='realtion',
            new_name='user',
        ),
    ]
